# NUMPY

In [1]:
import numpy as np


In [4]:
a = np.array([10,20,30])
print(a)
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>


In [6]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr)

[[10 20 30 40]
 [50 60 70 80]]


In [8]:
arr = np.array([10,20,30,40])
print(arr)
print(arr[0:3])

[10 20 30 40]
[10 20 30]


In [16]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:3])
print(arr[0,1:3])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))

[[10 20 30]
 [50 60 70]]
[20 30]
(2, 4)
8
2


In [25]:
a = [[30,40,40],[40,30,10]]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))

[[30 40 40]
 [40 30 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 40. 40.]
 [40. 30. 10.]]


In [28]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [40 30]]
[[60 60]
 [40 30]]


In [30]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [  0 -10]]
[[  0  20]
 [  0 -10]]


In [32]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [400 200]]
[[900 800]
 [400 200]]


In [31]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [1.  0.5]]
[[1.  2. ]
 [1.  0.5]]


In [33]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([3])
print(np.power(arr1,arr2))

[27 64  8  1]


In [34]:
arr1 = np.array([27,64,8,1])
print(np.sqrt(arr1))

[5.19615242 8.         2.82842712 1.        ]


In [35]:
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [40]:
arr1 = np.array([30,40,50])
print(np.append(arr1,[90]))
print(np.sort(arr1))
print(np.where(arr1 ==40))

[30 40 50 90]
[30 40 50]
(array([1]),)


In [41]:
arr1 = np.array([30,40,50])
print(np.sum(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.size(arr1))
print(np.mean(arr1))

120
30
50
3
40.0
